### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by kmruiz** [rxmqjs/rxmq.js#12]
I'm using Rxmq with Angular and would be nice to have typings support for ts autocomplete. I made my own typing file (for the basic usage I do) so, if it's ok, I'll like to have it bundled with the rxmq package so it works automagically:

```typescript
import { Observable, Subject } from 'rxjs';

declare namespace Rxmq {
    interface Channel {
        observe<T>(topic: String): Observable<T>
        subject<T>(topic: String): Subject<T>
    }

    function channel(name: String): Channel    
}

export default Rxmq;
```

**Comment by yamalight** [comment]
Hi @kmruiz! I haven't really worked with TS that much, so I have no idea how to bundle typings like this.
If you could send a PR - I'd be happy to accept it. 😄
