### ISSUE TITLE
add BehaviorSubject

### ISSUE THREAD

**Issue by cpete** [rxmqjs/rxmq.js#14]
It would be great to also have a BehaviorSubject where you can specify a default value (in the case that no data was provided, yet).

A BehaviorSubject "represents a value that changes over time. Observers can subscribe to the subject to receive the last (or initial) value and all subsequent notifications." (taken from [rxjs documentation BehaviorSubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md)

**Comment by yamalight** [comment]
@cpete you can pass the subject class used for specific subject during its initial creation like so:
```js
const subj = Rxmq.channel('test').subject('behave', {Subject: BehaviorSubject});
```
If that's enough - please, close the issue. 
If not - let me know what use case it doesn't fit and I'll think on how best to address it :)

**Comment by cpete** [comment]
@yamalight Thanks very much, that works.

**Comment by yamalight** [comment]
@cpete great 👍
