### ISSUE TITLE
channel.subject() method missing in d.ts definitions

### ISSUE THREAD

**Issue by kirillgroshkov** [rxmqjs/rxmq.js#17]
I'm trying to do `channel.subject()` according to documentation, but `.d.ts` typings show me error (no such method). So either documentation or `.d.ts` is wrong. Help!

**Comment by yamalight** [comment]
@kirillgroshkov method is definitely [there](https://github.com/rxmqjs/rxmq.js/blob/master/src/channel.js#L58), but it does indeed looks like it's not in `.d.ts` [definition](https://github.com/rxmqjs/rxmq.js/blob/master/ts/channel.d.ts).
I am not too familiar with typescript, so PR to fix that would be appreciated!

**Comment by yamalight** [comment]
@amiram thanks for reminder :)
