### ISSUE TITLE
Enhancement?

### ISSUE THREAD

**Issue by gnimmelf** [rxmqjs/rxmq.js#20]
Hi,

sort of new to all this (FRP stuff), but love what you are doing. As a lazy guy, I am wondering if it'd be possible to chain some kind of `.store("category")` to all "subscriptions" (not sure what that would be in RxJs terms) returned?

Usage would be
```
  const cartChannel = utils.channel('cart');

  cartChannel
    .subject('item.quantity.decremented')
    .subscribe((cartItemData) => actions.incrementAvailability(cartItemData.date));
    .store('service-availability');

  cartChannel
    .subject('item.added')
    .subscribe((cartItemData) => actions.decrementAvailability(cartItemData.date));
    .store('service-availability');
```

-And then just do `channel.unsubscribe('service-availability');` 

-Maybe this is doable allready somehow using Rx/Js?

Cheers!

PS! I'm using this in the browser with jQuery (one foot in the past).

**Comment by yamalight** [comment]
Hi @gnimmelf! 
Can you please explain what should `.store('category')` do in your examples? And what should `.unsubscribe('category')` do as well.
I am not sure I understand them correctly

**Comment by gnimmelf** [comment]
Hi, 

I'm using a lot of closures to send data on channel subscriptions (due to DOM and data replaced when sections of the page are updated), so I need to unsubscribe before the entire section is replaced, and a new set of identical subscriptions are made. It's a weird, hybrid setup...

So am wondering if all the subscriptions made during one rendering of a section can be automagically stored and then unsubscribed.

Right now I'm wrapping it, which is working, but not as elegant. 
```
storeSubscription('service-availability', cartChannel
   .subject('item.quantity.decremented')
   .subscribe((cartItemData) => actions.incrementAvailability(cartItemData.date)));
 
storeSubscription('service-availability', cartChannel
    .subject('item.added')
    .subscribe((cartItemData) => actions.decrementAvailability(cartItemData.date)));
```

and then to unsubscribe before a new rendering:
```
unsubscribe(''service-availability')
``` 

Hope this helps. Like I said, I'm new to this, so if there is a perferred way of doing this, I'd love to know.

Thanks!

**Comment by yamalight** [comment]
Ah, I see. The way you are doing it sounds fine.
I think the case itself is too specific to implement it inside of core. 
If you want to see it as a part of rxmq - you could implement it as a plugin. That should be relatively easy to do.

**Comment by gnimmelf** [comment]
Ok, nice,

I'll keep the plugin in mind for when I have more experience and not crunch-time =)

Closing!

Thank you!
