### ISSUE TITLE
Provide buffer size for ReplaySubject

### ISSUE THREAD

**Issue by rmeshksar** [rxmqjs/rxmq.js#23]
Hi,
My question is related to this change:
https://github.com/rxmqjs/rxmq.js/issues/4

If I want to set the Subject as EndlessReplaySubject, how can I provide the buffer size and it is the ReplaySubject constructor parameter?

Thanks.

**Comment by yamalight** [comment]
Hi @rmeshksar,
I'd say the best way would be to subclass ReplaySubject and specify the buffer you need in the constructor.

**Comment by rmeshksar** [comment]
Thanks. The following works as you suggested:

```javascript
import { EndlessReplaySubject } from 'Rxmq';

export class CustomReplaySubject<T> extends EndlessReplaySubject<T> {

  constructor() {
    super(1);
  }
}

```

And then I provide CustomReplaySubject to the subject method of the channel.
