### ISSUE TITLE
ESDoc Hosting Service

### ISSUE THREAD

**Issue by h13i32maru** [rxmqjs/rxmq.js#7]
Hi!
I am ESDoc developer and thanks for using ESDoc :smile: 

I released [ESDoc Hosting Service](https://doc.esdoc.org) :rocket: 
Register your repository Git URL, this service automatically generate documentation.
If you are interested, please try to use it.
Thanks

**Comment by yamalight** [comment]
@h13i32maru oh, that looks pretty cool! Will definitely try it out once I have some free time (probably this weekend). Will let you know how it goes :smile:

**Comment by yamalight** [comment]
@h13i32maru finally found some time - [it's done](https://doc.esdoc.org/github.com/rxmqjs/rxmq.js/)! pretty neat and easy :D
